/**
 * Test set RAGAS — 50 perguntas representativas de ISPs.
 * Usado pelo CI job para validar a qualidade do RAG em cada deploy.
 */
import type { RagSample } from './ragas';

export const ISP_TEST_SET: Omit<RagSample, 'answer' | 'contexts'>[] = [
  { question: 'Minha internet caiu, o que eu faço?', groundTruth: 'Reinicie o roteador, verifique cabos, se persistir abra chamado.' },
  { question: 'Qual o valor da minha mensalidade?', groundTruth: 'O valor depende do plano contratado, consultar no ERP.' },
  { question: 'Como faço para trocar meu plano?', groundTruth: 'Entre em contato com o atendimento ou acesse o portal.' },
  { question: 'Posso pagar meu boleto pelo PIX?', groundTruth: 'Sim, use o QR code que acompanha o boleto.' },
  { question: 'Meu boleto venceu, tem multa?', groundTruth: 'Após o vencimento incide multa de 2% + juros.' },
  { question: 'Quando vence minha fatura?', groundTruth: 'A data de vencimento está indicada na fatura.' },
  { question: 'Minha velocidade está lenta, o que fazer?', groundTruth: 'Teste com cabo ethernet direto no roteador, verifique se a banda contratada confere.' },
  { question: 'Como faço para cancelar meu plano?', groundTruth: 'Solicite o cancelamento pelo atendimento; multa pode aplicar se antes da fidelidade.' },
  { question: 'Vocês fazem instalação no meu bairro?', groundTruth: 'Consulte a cobertura pelo mapa ou informe seu endereço.' },
  { question: 'Preciso de uma segunda via do boleto', groundTruth: 'Acesse o portal do assinante ou solicite pelo WhatsApp.' },
  { question: 'O técnico não apareceu na data marcada', groundTruth: 'Pedimos desculpas, vamos reagendar com prioridade.' },
  { question: 'Meu roteador está com luz vermelha', groundTruth: 'Luz vermelha geralmente indica perda de sinal (fibra), abra chamado técnico.' },
  { question: 'Quanto custa o plano de 500 Mbps?', groundTruth: 'Consulte os planos atualizados no portal ou com o vendedor.' },
  { question: 'Tenho desconto se pagar em dia?', groundTruth: 'Depende da política do provedor, alguns oferecem desconto pontualidade.' },
  { question: 'Meu Wi-Fi não funciona mas o cabo sim', groundTruth: 'Verifique a configuração do Wi-Fi no roteador, pode ser canal congestionado.' },
  { question: 'Como altero a senha do meu Wi-Fi?', groundTruth: 'Acesse 192.168.0.1 ou 192.168.1.1 no navegador com as credenciais do roteador.' },
  { question: 'A internet oscila durante o dia', groundTruth: 'Pode ser congestionamento na CTO, abra chamado para análise.' },
  { question: 'Vocês têm plano para empresa?', groundTruth: 'Sim, temos planos corporativos com SLA e IP fixo.' },
  { question: 'Quero mudar o dia de vencimento', groundTruth: 'Solicite pelo atendimento, disponível entre dia 5 e 25.' },
  { question: 'Minha OS foi cancelada sem me avisar', groundTruth: 'Vamos verificar no sistema e reagendar com prioridade.' },
  { question: 'O roteador reinicia sozinho', groundTruth: 'Pode ser problema de alimentação ou firmware, solicite troca de equipamento.' },
  { question: 'Não consigo acessar o portal do assinante', groundTruth: 'Verifique se o link está correto e tente limpar cache do navegador.' },
  { question: 'Vocês oferecem TV por assinatura?', groundTruth: 'Depende do provedor, consulte planos combo disponíveis.' },
  { question: 'Preciso de IP fixo para minha câmera', groundTruth: 'Temos plano com IP fixo, consulte valores.' },
  { question: 'Minha fibra quebrou no poste', groundTruth: 'Abra chamado emergencial, equipe técnica será enviada.' },
  { question: 'Posso usar meu próprio roteador?', groundTruth: 'Sim, em modo bridge na ONU, configuração por conta do cliente.' },
  { question: 'Qual a diferença entre fibra e rádio?', groundTruth: 'Fibra tem menor latência e maior estabilidade; rádio é via antena.' },
  { question: 'O download está bom mas o upload não', groundTruth: 'Verifique se seu plano tem upload simétrico ou assimétrico.' },
  { question: 'Quero indicar um amigo, tem desconto?', groundTruth: 'Sim, programa de indicação: você ganha desconto se seu indicado ativar.' },
  { question: 'Não recebi o boleto este mês', groundTruth: 'Gere a segunda via no portal ou solicite pelo WhatsApp.' },
  { question: 'Vocês instalam em área rural?', groundTruth: 'Consulte a viabilidade técnica informando seu endereço.' },
  { question: 'O PPPoE não conecta', groundTruth: 'Verifique usuário e senha do PPPoE, podem estar incorretos.' },
  { question: 'Meu ping está alto no jogo online', groundTruth: 'Teste com cabo ethernet, feche downloads paralelos, pode ser rota.' },
  { question: 'A internet só funciona em um cômodo', groundTruth: 'Sinal fraco do Wi-Fi, considere repetidor ou mesh.' },
  { question: 'Quero aumentar a velocidade', groundTruth: 'Solicite upgrade de plano pelo atendimento.' },
  { question: 'O Netflix trava mas o YouTube não', groundTruth: 'Pode ser problema de rota ou capacidade do dispositivo, teste em outro.' },
  { question: 'Vocês têm telefone fixo VoIP?', groundTruth: 'Sim, plano VoIP disponível como adicional.' },
  { question: 'Meu contrato vence quando?', groundTruth: 'Consulte a data de adesão e período de fidelidade no portal.' },
  { question: 'O que é CTO e ONU?', groundTruth: 'CTO é a caixa de distribuição no poste; ONU é o equipamento na sua casa.' },
  { question: 'Preciso trocar o roteador?', groundTruth: 'Se está lento e antigo, pode ser necessário; sugerimos dual-band AC.' },
  { question: 'Vocês fazem manutenção preventiva?', groundTruth: 'Sim, manutenção preventiva na rede é feita regularmente.' },
  { question: 'Meu vizinho tem internet e eu não', groundTruth: 'Pode ser problema na sua fibra específica, abra chamado.' },
  { question: 'Qual o horário de atendimento?', groundTruth: 'Atendimento via WhatsApp 24/7, suporte técnico em horário comercial.' },
  { question: 'Posso parcelar minha dívida?', groundTruth: 'Sim, entre em contato para negociar parcelamento.' },
  { question: 'A luz do ONU está piscando', groundTruth: 'PON piscando = sem sinal óptico, possível rompimento.' },
  { question: 'Quero mudar o endereço da instalação', groundTruth: 'Solicite a mudança de endereço, pode haver taxa.' },
  { question: 'Meu Wi-Fi 5GHz não aparece', groundTruth: 'Verifique se o dispositivo suporta 5GHz e se está habilitado no roteador.' },
  { question: 'Vocês bloqueiam a internet quando atrasa?', groundTruth: 'Após X dias de atraso, pode haver suspensão conforme contrato.' },
  { question: 'Como faço para tirar nota fiscal?', groundTruth: 'Notas fiscais são emitidas automaticamente, consulte no portal.' },
  { question: 'O que acontece se eu não devolver o equipamento?', groundTruth: 'Equipamento é comodato, não devolução gera cobrança.' },
];
